// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv7hLSNqg8bP10jcOTrRKUoIvFGVQhCvo',
    appId: '1:921846706296:web:79b9bbb05e49ea4a757d8d',
    messagingSenderId: '921846706296',
    projectId: 'green-a22a7',
    authDomain: 'green-a22a7.firebaseapp.com',
    storageBucket: 'green-a22a7.firebasestorage.app',
    measurementId: 'G-DY321PPY7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATumktVDVlMIHj9Vq0ZeB018KC6aNhHKc',
    appId: '1:921846706296:android:6c47eca2bf9aa09b757d8d',
    messagingSenderId: '921846706296',
    projectId: 'green-a22a7',
    storageBucket: 'green-a22a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwx24rAhkKfGidJl1aZPlXIC4x4vByiDc',
    appId: '1:921846706296:ios:9808a429e5f664d7757d8d',
    messagingSenderId: '921846706296',
    projectId: 'green-a22a7',
    storageBucket: 'green-a22a7.firebasestorage.app',
    iosBundleId: 'com.example.green',
  );
}
